on: [push]
jobs:
    create_pdf:
        runs-on: ubuntu-18.04
        name: Create PDF out of main.tex
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build docker
              run: docker build -t mydocker .
            - name: Run docker
              run: docker run -i --mount type=bind,source="$(pwd)"/src,target=/src mydocker /bin/bash
            - name: hmmm2
              uses: actions/upload-artifact@v2
              with:
                name: cv
                path: /src/main.pdf
            - name: Download PDF file
              uses: actions/download-artifact@v2
              with:
                name: cv
