on: [push]
jobs:
    create_pdf:
        runs-on: ubuntu-18.04
        name: Create PDF out of main.tex
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build docker
              run: docker build -t mydocker .
            - name: Run docker
              run: docker run -i mydocker /bin/bash
            - name: Generated PDF file
              uses: actions/upload-artifact@v2
              with:
                name: main.pdf
                path: main.pdf
